### ISSUE TITLE
Port request (REminiscence v1.0)

### ISSUE THREAD

**Issue by jutleys** [steward-fu/gh_retrogame_emulator#127]
https://boards.dingoonity.org/gcw-releases/reminiscence-port-beta-released!/

**Comment by steward-fu** [comment]
done, kindly help to check it
https://github.com/steward-fu/gh_retrogame_binary

**Comment by jutleys** [comment]
I copied the files over all of them and it does not start just resets back
to home screen.

**Comment by steward-fu** [comment]
list out the folder:  /mnt/int_sd/games/reminiscence

**Comment by jutleys** [comment]
Its working if i go to explorer and run  the file called rs but it wont run
from gmenu2x

**Comment by jutleys** [comment]
these are the folders i have

data
rs   <(if i click this it works)
rs-level1-01.state
run.dge
