### ISSUE TITLE
Snes9x4d Aspect Ratio

### ISSUE THREAD

**Issue by dudedupe** [steward-fu/gh_retrogame_emulator#131]
Could you please fix the aspect ratio to pixel perfect for Snex9x4d when the fullscreen setting is off? Currently the display is distorted and squeezed to half of the screen. Many thanks for your hard work!

**Comment by steward-fu** [comment]
fixed:
https://github.com/steward-fu/gh_retrogame_binary/blob/master/Snes9x4D/int_sd/emus/snes9x4d/snes9x4d.dge

**Comment by dudedupe** [comment]
Thank you very much for your quick turnaround on this! This is so far the best emulator that runs Metal Max Returns at 60 fps full speed. Thanks again and i'm closing this issue now.
