### ISSUE TITLE
[Port Request] Tile World

### ISSUE THREAD

**Issue by mbaran5** [steward-fu/gh_retrogame_emulator#146]
Was hoping you could port https://github.com/senquack/tileworld-for-handhelds to RS97. I attempted to, but it segfaults.

**Comment by steward-fu** [comment]
miss data files.
could you kindly help to provide it to me ?

**Comment by mbaran5** [comment]
Here’s a free pack: https://www.dropbox.com/s/r5mstmsfh8ygp9b/CCLP1.zip?dl=0

Here’s a site with a large archive of level packs
http://www.pillowpc2001.net/?i=1

When I tried to port the game myself it compiled OK but segfaulted trying to omit SDL


Sent from my iPhone
________________________________

**Comment by steward-fu** [comment]
porting complete:
https://github.com/steward-fu/gh_retrogame_binary
https://github.com/steward-fu/gh_retrogame_emulator

**Comment by steward-fu** [comment]
kindly close this feature request if complete.
Thanks :)
