### ISSUE TITLE
Slow boot up

### ISSUE THREAD

**Issue by jutleys** [steward-fu/gh_retrogame_emulator#3]
Device takes longer to boot up than normal once games are copied over to roms folder

**Comment by steward-fu** [comment]
Since getDiskFree() will take more time than my expectation, so, currently, I will use workaround (don't show disk free space instead).
Workaround on v20180213

**Comment by steward-fu** [comment]
CreateThread() for sync disk space when start up gmenu2x.
reopen it

**Comment by steward-fu** [comment]
Finally, I decided to remove DiskFree information on v20180213 and added sdcard icon when insert external icon on status bar.
