### ISSUE TITLE
Opendingux splash screen

### ISSUE THREAD

**Issue by onthebridge** [steward-fu/gh_retrogame_emulator#30]
Please add an opendingux splash screen when you switch on the handheld

**Comment by steward-fu** [comment]
is it possible to provide it to me.
thanks

**Comment by onthebridge** [comment]
Sure thing
![opendinguxsplash2](https://user-images.githubusercontent.com/2809342/36065394-f69bd18a-0e91-11e8-93e1-43bc96c330b9.jpg)
![opendinguxsplash3](https://user-images.githubusercontent.com/2809342/36065395-f6c616d4-0e91-11e8-9647-54dc8ebac294.jpg)

**Comment by jutleys** [comment]
Yes it would be great to get rid of the existing boot logo and replace it with this one

**Comment by steward-fu** [comment]
Added opendingux splash on v20180213.

Since the default boot logo is controlled by kernel, it will take more time to patch it for new boot logo.
So, I will keep it.

**Comment by steward-fu** [comment]
please close it
