### ISSUE TITLE
Extend the game partition upgrade error

### ISSUE THREAD

**Issue by jutleys** [steward-fu/gh_retrogame_emulator#49]
I wanted to extend the game partition higher to 16gb when you try to run the upgrade official firmware fails to mount and upgrade fails. Could you try and fix this It might be looking for the original file size of the game partition because its been changed to 16gb or more.

**Comment by steward-fu** [comment]
upgrade firmware just do mount and umount.
it will not effect the partition size.
could you provide the sha1 value of your upgrade.ext3 file.

**Comment by jaZzKCS** [comment]
Is it possible to extend the game partition after doing a full flash installation?
As in: First flash the entire .img version and then extend the partition manually? Will the device be bothered?

**Comment by steward-fu** [comment]
sure, I will consider it.
but I want to know what's the means of "Extend the game partition upgrade error" ?

**Comment by jutleys** [comment]
I am trying to install on 128gb card when i upgrade it keeps saying mount failed

**Comment by jutleys** [comment]
I have not touched any partitions yet only default ones.

**Comment by steward-fu** [comment]
do you have installed beta os on this 128gb sdcard ?

**Comment by jutleys** [comment]
Sorry Steward its my fault i was extracting upgrade files to game folder instead of the roms folder problem solved.

**Comment by jutleys** [comment]
Thank you for your help.

**Comment by steward-fu** [comment]
btw, do you have pap k3 (7 days... all of default pre-installed games), please provide to me.
I would like to porting even reverse engineering to retro game.
thanks

**Comment by steward-fu** [comment]
good. hope you enjoy !

**Comment by jutleys** [comment]
I have extended the game partition to 16gb and 100gb for roms partition i like this setup.

**Comment by jutleys** [comment]
I have the original  .img file here
https://drive.google.com/file/d/0B0wz_n5he9GpQW96allVTUJNSnM/view

**Comment by jutleys** [comment]
I have the original  .img file here https://drive.google.com/file/d/0B0wz_
n5he9GpQW96allVTUJNSnM/view

**Comment by steward-fu** [comment]
thanks :)
I will try to port to RetroGame device

**Comment by jutleys** [comment]
Cool

**Comment by steward-fu** [comment]
I cannot see any pre-installed game like 7-days.
do you have seen them on pap k3 ?

**Comment by jutleys** [comment]
I never saw that game all my roms were preinstalled english maybe you need
someone with papkiii plus with the chinese rom preinstalled that could have
the game on there.

**Comment by steward-fu** [comment]
got it, thanks
