### ISSUE TITLE
[pcsx4all] Triangle button (x-button on device) not mapped / not working.

### ISSUE THREAD

**Issue by jaZzKCS** [steward-fu/gh_retrogame_emulator#59]
The x-button on the device (upper button), which corresponds to the PSX "triangle"-button, is not mapped it seems, resulting in not working in emulation. There is no option to change the controller settings in the emulator menu, therefore I open up this ticket.

Is there a settings file I could modify manually for this button to be mapped correctly?

**Comment by jaZzKCS** [comment]
Can someone direct me to the config file I need to change if that is possible? A non-working triangle button kind of hinders me to test further.

**Comment by steward-fu** [comment]
which game do you play in pcsx4all ?

**Comment by jaZzKCS** [comment]
I tested out FFVII and Tekken 3 so far and noticed the triangle button not working on both games, therefore concluded it isnt mapped.

**Comment by steward-fu** [comment]
after check with Raiden rom, X button is work.
could you kindly help to check whether it is different withwithout HLE bios

**Comment by jaZzKCS** [comment]
Sorry, I can't. It starts with HLE enabled. When going into settings and turning it off, exiting the emulator and restart, it didnt save the setting (it's on again). And when changing the setting and not exiting, but going back to emulation, it crashes. I cannot turn it off, it wont save it :(

**Comment by jaZzKCS** [comment]
Please close this issue, it turned out my unit had a hardware fault (capacitor missing for "x"-button, they are very small and it's easy overlook that one is missing.)

**Comment by steward-fu** [comment]
thanks
