### ISSUE TITLE
界面功能性优化建议

### ISSUE THREAD

**Issue by lfmmd** [steward-fu/gh_retrogame_emulator#60]
在打开模拟器的时候，默认所有的app都是打开mnt目录。这个可能不是特别友好，是否可以实现每一个app默认打开的文件夹目录位置

**Comment by lfmmd** [comment]
好像已经实现了  不需要了

**Comment by steward-fu** [comment]
編輯  選擇器路徑就可以，如解決，請關閉這個問題
