### ISSUE TITLE
[Feature Request] Port of several emulators

### ISSUE THREAD

**Issue by onthebridge** [steward-fu/gh_retrogame_emulator#63]
̶A̶m̶s̶t̶r̶a̶d̶ ̶C̶P̶C̶ ̶h̶t̶t̶p̶s̶:̶/̶/̶b̶o̶a̶r̶d̶s̶.̶d̶i̶n̶g̶o̶o̶n̶i̶t̶y̶.̶o̶r̶g̶/̶g̶c̶w̶-̶r̶e̶l̶e̶a̶s̶e̶s̶/̶c̶a̶p̶r̶i̶c̶e̶3̶2̶-̶(̶a̶m̶s̶t̶r̶a̶d̶-̶c̶p̶c̶)̶/̶
 ̶A̶m̶i̶g̶a̶ ̶5̶0̶0̶ ̶h̶t̶t̶p̶s̶:̶/̶/̶b̶o̶a̶r̶d̶s̶.̶d̶i̶n̶g̶o̶o̶n̶i̶t̶y̶.̶o̶r̶g̶/̶g̶c̶w̶-̶r̶e̶l̶e̶a̶s̶e̶s̶/̶u̶a̶e̶4̶a̶l̶l̶-̶r̶e̶l̶e̶a̶s̶e̶-̶1̶/̶
 ̶̶̶S̶̶̶p̶̶̶e̶̶̶c̶̶̶t̶̶̶r̶̶̶u̶̶̶m̶̶̶ ̶̶̶4̶̶̶8̶̶̶/̶̶̶1̶̶̶2̶̶̶8̶̶̶k̶̶̶ ̶̶̶h̶̶̶t̶̶̶t̶̶̶p̶̶̶s̶̶̶:̶̶̶/̶̶̶/̶̶̶b̶̶̶o̶̶̶a̶̶̶r̶̶̶d̶̶̶s̶̶̶.̶̶̶d̶̶̶i̶̶̶n̶̶̶g̶̶̶o̶̶̶o̶̶̶n̶̶̶i̶̶̶t̶̶̶y̶̶̶.̶̶̶o̶̶̶r̶̶̶g̶̶̶/̶̶̶g̶̶̶c̶̶̶w̶̶̶-̶̶̶r̶̶̶e̶̶̶l̶̶̶e̶̶̶a̶̶̶s̶̶̶e̶̶̶s̶̶̶/̶̶̶u̶̶̶n̶̶̶r̶̶̶e̶̶̶a̶̶̶l̶̶̶-̶̶̶s̶̶̶p̶̶̶e̶̶̶c̶̶̶c̶̶̶y̶̶̶-̶̶̶p̶̶̶o̶̶̶r̶̶̶t̶̶̶a̶̶̶b̶̶̶l̶̶̶e̶̶̶-̶̶̶0̶̶̶-̶̶̶0̶̶̶-̶̶̶5̶̶̶9̶̶̶/̶̶̶
̶̶X̶̶̶M̶̶̶A̶̶̶M̶̶̶E̶̶̶ ̶̶̶h̶̶̶t̶̶̶t̶̶̶p̶̶̶:̶̶̶/̶̶̶/̶̶̶w̶̶̶w̶̶̶w̶̶̶.̶̶̶s̶̶̶l̶̶̶a̶̶̶a̶̶̶n̶̶̶e̶̶̶s̶̶̶h̶̶̶.̶̶̶n̶̶̶e̶̶̶t̶̶̶/̶̶̶2̶̶̶0̶̶̶1̶̶̶4̶̶̶/̶̶̶1̶̶̶2̶̶̶/̶̶̶x̶̶̶m̶̶̶a̶̶̶m̶̶̶e̶̶̶-̶̶̶v̶̶̶1̶̶̶0̶̶̶-̶̶̶f̶̶̶o̶̶̶r̶̶̶-̶̶̶g̶̶̶c̶̶̶w̶̶̶-̶̶̶z̶̶̶e̶̶̶r̶̶̶o̶̶̶.̶̶̶h̶̶̶t̶̶̶m̶̶̶l̶̶̶

**Comment by tackro** [comment]
slaanesh is a great person, if someone contact his i think he will help with this, aside, their emulator are good and optimized

**Comment by steward-fu** [comment]
for xmame, I have ported but still need to fix some things like failed to load *.bin file.
for other emulators, I will add into porting list.

**Comment by steward-fu** [comment]
xmame can run on RetroGame but with very low fps and sound lag.
I will put it into low priority list.
Amstrad CPC and Amiga 500 will be take and port soon.

**Comment by steward-fu** [comment]
Amstrad CPC has been ported to RetroGame and will  be included in next release.
package (put under /mnt/game/cap32/):
https://drive.google.com/file/d/1COaCJ-IHUdR4pDEucniTaC-06U3jdkmH/view?usp=sharing

**Comment by steward-fu** [comment]
Amiga 500 has been ported to RetroGame and will be included in next release.
package (put under /mnt/game/uae4all):
https://drive.google.com/file/d/1Ft7wSwutFdGG-OnuLPqs0w0FZJSIlW3W/view?usp=sharing

**Comment by onthebridge** [comment]
Amazing Steward, thank you very much :D
