### ISSUE TITLE
tv-out

### ISSUE THREAD

**Issue by tackro** [steward-fu/gh_retrogame_emulator#65]
tv out ins't working
if not much asking, can configure the tv-out to headphone jack (inferior part)?

**Comment by steward-fu** [comment]
currently, it is not add into GMenu2X, I will add it into next release but need your verification, thanks

**Comment by tackro** [comment]
@steward-fu I can test for sure, just give me a hint 👍

**Comment by jaZzKCS** [comment]
Why should the TV-out be routed away from the AV-out to the headphone jack? And which jack is inferior, If I might ask?

**Comment by steward-fu** [comment]
1. tvout can only output on AV-out port
2. this issue will be included in v20180313

**Comment by tackro** [comment]
Is it possible to solder the 3.5mm jack on TV out?

Em 19 de fev de 2018 10:50, Steward Fu <notifications@github.com> escreveu:

  1.  tvout can only output on AV-out port
  2.  this issue will be included in v20180313
