### ISSUE TITLE
[Port request] uNGP - Neo Geo Pocket Emulator

### ISSUE THREAD

**Issue by tackro** [steward-fu/gh_retrogame_emulator#66]
here's the code:
https://code.google.com/archive/p/developia/source

**Comment by tackro** [comment]
RACEOD is another emulator, here's the code
http://dingoo.a320.free.fr/downloads/emuls_opendingux/neogeo_pocket/race-od_v10_src.zip

**Comment by steward-fu** [comment]
thanks for your information, I will port this soon

**Comment by tackro** [comment]
@steward-fu I marked you on dingoonity, I tried to run RACE-OD with sdlfix.so and emulator runned but no image, but can hear the sounds of game. When execute without sdlfix it gave double screen (30fps on which screen)

**Comment by steward-fu** [comment]
for sdlfix, since I don't know what issue causes according to the description. so, you can use gdb to debug this issue
https://github.com/steward-fu/gh_retrogame_dev

but it needs uart debug port for debugging

**Comment by steward-fu** [comment]
by the way, I will also fix double screen issues in sdl library soon because fix each emulators are not good idea.

**Comment by steward-fu** [comment]
1. race-od have been posted on dingoonity forum for testing and it will be added into next release list.
2. finally, I decide to give up fix double screen in lib sdl because it is more difficult.
if you can shared the sdlfix source code, I can help to check it.
thanks

**Comment by steward-fu** [comment]
kindly help to check race-od emulator again and feedback issue:
https://drive.google.com/file/d/1nD4zXaFb72uaPKwZd3jse0yynS_0vu5i/view?usp=sharing

**Comment by steward-fu** [comment]
Since uNGP source code is not available anymore, ignore uNGP emulator.

**Comment by tackro** [comment]
Framerate now is better on native res (around 47-50fps) but when change rom, the menu still on screen (only when select native resolution). On fullscreen still the same, 30fps on all games.

**Comment by steward-fu** [comment]
bugfix: skin redraw issue
https://drive.google.com/file/d/14iRbuBpEn7Alvvz8j3hRPutLHHAf4IDv/view?usp=sharing

for performance issue, I will reply in another issue you submitted.
thanks

**Comment by steward-fu** [comment]
please kindly help to provide the 32x32 png icon for gmenu2x with background transparency.

**Comment by tackro** [comment]
Emulator aspect ratio change it's fixed, thanks.
There's only a strange horizontal line on top of screen but its a minor.
Framerate is ok on aspect ratio, 50fps, playable.

**Comment by steward-fu** [comment]
this is original picture for skin:
https://drive.google.com/file/d/1XxF_lO9E1NqImaUXGbJt62v1STRAqIYm/view?usp=sharing

if you can provide new one, I can help to update it,
thanks

**Comment by steward-fu** [comment]
Fix: extension name issue
https://drive.google.com/file/d/1K6_0E37H84vP1G5jfLfA7hKTch7GbMY-/view?usp=sharing
