### ISSUE TITLE
[Port request] Streets of Rage Remake 5.1

### ISSUE THREAD

**Issue by tackro** [steward-fu/gh_retrogame_emulator#79]
there's already a port for gcw zero and a BennuGD+SoRR for dingux, but I wasn't able to find the sources, only the OPK, but Hi-Ban (user on dingoonity) got it (i guess)

**Comment by steward-fu** [comment]
Please provide source code.

**Comment by steward-fu** [comment]
after ported engine "bennugd", now, this game can run on RetroGame but the fps is not good.
I will continue to do optimization.
thanks

**Comment by tackro** [comment]
How many fps

Em 20 de fev de 2018 10:54, Steward Fu <notifications@github.com> escreveu:

after ported engine "bennugd", now, this game can run on RetroGame but the fps is not good.
I will continue to do optimization.
thanks

**Comment by steward-fu** [comment]
fps is 40 when overclock to 618Mz

**Comment by tackro** [comment]
600+ overclock is secure?

Em 20 de fev de 2018 13:41, Steward Fu <notifications@github.com> escreveu:

fps is 40 when overclock to 618Mz
