### ISSUE TITLE
No automatic reboot after plugging in charge cable at low battery / Stuck at "low battery" splashscreen

### ISSUE THREAD

**Issue by jaZzKCS** [steward-fu/gh_retrogame_emulator#81]
Normally, with the original firmware, a blinking symbol would get displayed. When you then plug in a charging cable, it starts charging and continues to boot to the desktop.

With the custom firmware, the last step doesnt happen, hence you have to attach a loading cable and then press the reset button.

**Comment by steward-fu** [comment]
do you mean this device will not reboot into desktop when in poweroff status ?

**Comment by jaZzKCS** [comment]
What I mean is:

When you start your device and its low on battery, instead of booting normally it will show the blinking battery splashscreen.

Then, if you plug in a cable it would start charging, the blinking splashscreen goes away and it continues to boot. 

With your custom firmware this doesnt happen. You put in the charging cable but it will continue to endlessly show the blinking battery symbol. You cant shut it down, and you cannot boot either. The only thing you can then do is to press reset button. 

Wit

**Comment by jaZzKCS** [comment]
Huh, this is weird. Today when I wanted to start it up and got the low power splashscreen, it actually rebooted once the USB cable was attached, which it didn't do before on cfw, only on official fw.

This seems to be sporadic behaviour

**Comment by steward-fu** [comment]
basically, all of usb issues are related to kernel/hardware issue, not related to gmenu2x, hope you understand and kindly close this issue. thanks

**Comment by jaZzKCS** [comment]
"basically, all of usb issues are related to kernel/hardware issue, not related to gmenu2x, hope you understand and kindly close this issue. thanks"

@steward-fu Im sorry, but I cannot close issues (even ones I created), only you can! :P

**Comment by steward-fu** [comment]
ok, thanks :)
