### ISSUE TITLE
[Port Request] Sonic Robo Blast 2

### ISSUE THREAD

**Issue by Impish3000** [steward-fu/gh_retrogame_emulator#95]
Sonic Robo Blast 2 (Sonic fan game made in Doom Legacy, ported to GCWZero) - source: https://bitbucket.org/shin_nil/sonic-robo-blast-2-gcw-zero

**Comment by steward-fu** [comment]
worth to check it, I will check it soon, thanks for your information

**Comment by steward-fu** [comment]
try porting to retrogame but crash often, it will not be included in next release.
plase keep this issue open until porting is complete.
thanks

**Comment by steward-fu** [comment]
Finally, fix some issues and use dirty fix.
Now, it can work very well.
This game will be included in next release.
Thanks
